/* Copyright 2022 Patrick Elmquist
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

#include "pket.h"

/* THIS FILE WAS GENERATED!
 *
#include QMK_KEYBOARD_H
 * This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
    [_COLEMAK] = LAYOUT_wrapper(
      ________________COLEMAK_L1_5_______________,     ________________COLEMAK_R1_5_______________,
      ________________COLEMAK_L2_5_______________,     ________________COLEMAK_R2_5_______________,
      ________________COLEMAK_L3_5_______________,     ________________COLEMAK_R3_5_______________,
                                 ___THUMB_LEFT___,     ___THUMB_RIGHT__
    ),

    [_HANDS_DOWN] = LAYOUT_wrapper(
      ________________HANDS_DOWN_L1_5____________,     ________________HANDS_DOWN_R1_5____________,
      ________________HANDS_DOWN_L2_5____________,     ________________HANDS_DOWN_R2_5____________,
      ________________HANDS_DOWN_L3_5____________,     ________________HANDS_DOWN_R3_5____________,
                                 ___THUMB_LEFT___,     ___THUMB_RIGHT__
    ),

    [_CANARY] = LAYOUT_wrapper(
      ________________CANARY_L1_5________________,     ________________CANARY_R1_5________________,
      ________________CANARY_L2_5________________,     ________________CANARY_R2_5________________,
      ________________CANARY_L3_5________________,     ________________CANARY_R3_5________________,
                                 ___THUMB_LEFT___,     ___THUMB_RIGHT__
    ),

    [_LOWER] = LAYOUT_wrapper(
      ________________LOWER__L1_5________________,     ________________LOWER__R1_5________________,
      ________________LOWER__L2_5________________,     ________________LOWER__R2_5________________,
      ________________LOWER__L3_5________________,     ________________LOWER__R3_5________________,
                                 _______, _______,     KC_ENT,  _______
    ),

    [_RAISE] = LAYOUT_wrapper(
      ________________RAISE__L1_5________________,     ________________RAISE__R1_5________________,
      ________________RAISE__L2_5________________,     ________________RAISE__R2_5________________,
      ________________RAISE__L3_5________________,     ________________RAISE__R3_5________________,
                                 _______, _______,     _______, _______
    ),

    [_NAV] = LAYOUT_wrapper(
      ________________NAV_L1_5___________________,     ________________NAV_R1_5___________________,
      ________________NAV_L2_5___________________,     ________________NAV_R2_5___________________,
      ________________NAV_L3_5___________________,     ________________NAV_R3_5___________________,
                                 _______, _______,     _______, _______
    ),

    [_SYSTEM] = LAYOUT_wrapper(
      ________________SYSTEM_L1_5________________,     ________________SYSTEM_R1_5________________,
      ________________SYSTEM_L2_5________________,     ________________SYSTEM_R2_5________________,
      ________________SYSTEM_L3_5________________,     ________________SYSTEM_R3_5________________,
                                 _______, _______,     KC_ENT,  _______
    ),

    [_ADJUST] = LAYOUT_wrapper(
      ________________ADJUST_L1_5________________,     ________________ADJUST_R1_5________________,
      ________________ADJUST_L2_5________________,     ________________ADJUST_R2_5________________,
      ________________ADJUST_L3_5________________,     ________________ADJUST_R3_5________________,
                                 _______, _______,     _______, _______
    )
};

